### ISSUE TITLE
希望你们团队能早日公布这一出色工作的数据及代码呀！！

### ISSUE THREAD

**Issue by ychuest** [qiaoqiaoLF/MxDNA#2]
![image](https://github.com/user-attachments/assets/14d8444e-ea81-4305-a398-23c5b42b81ab)

**Comment by qiaoqiaoLF** [comment]
Thank you for your kind words and interest in our work! 🎉
We’re excited to share that we’ve open-sourced the full implementation. However, we currently do not have plans to release the training code or data. Building a distributed training loop should be straightforward and will depend on your local environment.

We hope the implementation is helpful, and we’re happy to answer any questions or discuss your ideas!
