### ISSUE TITLE
请问作者能公布Mxdna的训练代码了吗

### ISSUE THREAD

**Issue by ychuest** [qiaoqiaoLF/MxDNA#3]

**Comment by qiaoqiaoLF** [comment]
Thank you for your kind words and interest in our work! 🎉
We’re excited to share that we’ve open-sourced the full implementation. However, we currently do not have plans to release the training code or data. Building a distributed training loop should be straightforward and will depend on your local environment.
We hope the implementation is helpful, and we’re happy to answer any questions or discuss your ideas!

**Comment by qiaoqiaoLF** [comment]
Additionally, you can refer to the training code and data of DNABERT, which we followed as stated in the paper

**Comment by ychuest** [comment]
> Additionally, you can refer to the training code and data of DNABERT, which we followed as stated in the paper
谢谢！
